export const CartToggleTypes = {
  CART_TOGGLE_TYPES: "CART_TOGGLE_TYPES",
  ADD_TO_CART: "ADD_TO_CART",
  DISPLAY_CART_DETAILS: "DISPLAY_CART_DETAILS",
  REMOVE_ITEM_CART: "REMOVE_ITEM_CART",
  ADD_QUANTITY: "ADD_QUANTITY",
  REMOVE_QUANTITY: "REMOVE_QUANTITY",
};
export default CartToggleTypes;
